### ISSUE TITLE
2. One Sentence

### ISSUE THREAD

**Issue by cehatch** [cehatch/Soil-Moisture-Paper#4]
Writing Step 2: Articulate the story in one sentence.  If you have co-authors, verify that everyone agrees with this sentence.

**Comment by cehatch** [comment]
**_2. Single Sentence:_**
Variations in root-zone soil moisture has important implications for wetland restoration actions and the re-wilding of former cranberry bogs.
(Cosh revision) Root-zone soil moisture is a critical component of the re-establishment of a natural ecosystem within a former cranberry bog.

**Comment by ItoErika** [comment]
@cehatch  

Would "a functional wetland system" be possibly preferable to a "natural ecosystem"?  Might "natural" be too vague / ambiguous a term?

**Comment by cehatch** [comment]
@ItoErika 
Yes, that's probably an improvement - thanks!

**Comment by cehatch** [comment]
Root-zone soil moisture is a critical component of the re-establishment of a functional wetland system within a former cranberry bog.
